- hosts: #BARTERING nodes
  gather_facts: no
  vars: 
    
    group_name: 
  tasks:
    - name: Make bartering folder
      shell : mkdir -p bartering/{{ hostvars[inventory_hostname]['label'] }}
    - name: Copy bartering binary
      copy:
        src: bartering-protocol/bartering
        dest: bartering/{{ hostvars[inventory_hostname]['label'] }}
    - name: Copy bartering config file
      copy:
        src: bartering-protocol/config.yaml
        dest: "~"
   
    - name: copy FIO test file
      copy:
        src: bartering-protocol/fio_test.fio
        dest: "~"
    - name : Authorize execution of bartering binary
      shell: chmod u+x bartering/{{ hostvars[inventory_hostname]['label'] }}/bartering
    - name: Make data dir
      shell: mkdir -p data
      
    - name: Run bartering protocol
      shell: nohup ./bartering/{{ hostvars[inventory_hostname]['label'] }}/bartering {{ hostvars[ groups['BarteringBootstrap'][0]]['ip_address'] }} >/dev/null 2>&1 &
    - name: Install
      shell: pip install numpy

    - name: Run data writer
      shell: nohup fio fio_test.fio --output=fio_results.txt > fio_stdout.log 2> fio_stderr.log &
