- hosts: # bartering nodes
  gather_facts: no
  vars: 
    bootstrap_ip: "{{lookup('file','bartering-protocol/bootstrap_ip.txt')}}"
    group_name: 
  tasks:
    - name: Run bartering protocol
      shell: nohup bartering/{{ hostvars[inventory_hostname]['label'] }}/bartering {{ bootstrap_ip }} >/dev/null 2>&1 &